### ISSUE TITLE
[Facebook\WebDriver\Exception\UnknownServerException] The property '#/' contains additional properties ["w3c"] outside of the schema when none are allowed in chromeOptions

### ISSUE THREAD

**Issue by kjnanda** [browserstack/Codeception-BrowserStack#7]
Hi there,

I am facing the issue while running my tests with travis set up. So far it was working fine and suddenly, it started throwing the error. 

I am not sure what is missing or what should I update in configuration file to fix this error. 

Any help would be appreciated. 

-----

The acceptance.suite.file configuration.

```
class_name: AcceptanceTester
modules:
    enabled:
        - \Helper\Acceptance
        - WPWebDriver
        - Asserts
    config:
        WPWebDriver:
            host: 'hub-cloud.browserstack.com'
            port: 80
            browser: 'chrome'
            url: 'http://automation.test.me/'
            adminUsername: ''
            adminPassword: ''
            adminPath: '/wp-admin'
            capabilities:
                'browserstack.user': '<Username>'
                'browserstack.key': '%BROWSERSTACK_ACCESS_KEY%'
                'os': 'OS X'
                'os_version': 'mojave'
                'browserstack.debug': 'true'
                'browserstack.networkLogs': 'true'
                'build': '%TRAVIS_BUILD_NUMBER%'
                'project': 'Automation'
                'browserstack.local': 'true'
```

----

Please refer to this screenshot to see the error.

![Screenshot of Build #3697 - rtMediaWP_rtMedia - Travis CI](https://user-images.githubusercontent.com/15173772/59264177-2959a280-8c60-11e9-8915-a7ab6b0ad057.jpg)

----
Thanks,

Krupa
